wandb_version: 1

# Example variables below. Uncomment (remove leading '# ') to use them, or just
# delete and create your own.

epochs:
   desc: Number of epochs to train over
   value: 100
batch_size:
   desc: Size of each mini-batch
   value: 32
learn_rate:
  value: 0.01
layer_1_size:
  value: 8
layer_2_size:
  value: 16
img_width:
  value: 28
img_height:
  value: 28
data_augmentation:
  value: False
dense_layer_nodes:
  value: 100
