wandb_version: 1

# Example variables below. Uncomment (remove leading '# ') to use them, or just
# delete and create your own.

epochs:
  desc: Number of epochs to train over
  value: 100
hidden_nodes:
  desc: Size of the hidden layer
  value: 100
optimizer:
  desc: Gradient Descent Algorithm
  value: adam
dropout:
  desc: Dropout Rate
  value: 0.4
